version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: >
      bash -c "python products/manage.py makemigrations --noinput &&
      python products/manage.py migrate --noinput &&
      python products/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db